import { Piece } from '@/types'
export const piecesInitialState = [
  {
    id: `white-rook-1`,
    name: `rook`,
    position: [1, 8],
    player: `white`,
    history: [[1, 8]],
  },
  {
    id: `white-knight-1`,
    name: `knight`,
    position: [2, 8],
    player: `white`,
    history: [[2, 8]],
  },
  {
    id: `white-bishop-1`,
    name: `bishop`,
    position: [3, 8],
    player: `white`,
    history: [[3, 8]],
  },
  {
    id: `white-king-1`,
    name: `king`,
    position: [4, 8],
    player: `white`,
    history: [[4, 8]],
  },
  {
    id: `white-queen-1`,
    name: `queen`,
    position: [5, 8],
    player: `white`,
    history: [[5, 8]],
  },
  {
    id: `white-bishop-2`,
    name: `bishop`,
    position: [6, 8],
    player: `white`,
    history: [[6, 8]],
  },
  {
    id: `white-knight-2`,
    name: `knight`,
    position: [7, 8],
    player: `white`,
    history: [[7, 8]],
  },
  {
    id: `white-rook-2`,
    name: `rook`,
    position: [8, 8],
    player: `white`,
    history: [[8, 8]],
  },
  {
    id: `white-pawn-1`,
    name: `pawn`,
    position: [1, 7],
    player: `white`,
    history: [[1, 7]],
  },
  {
    id: `white-pawn-2`,
    name: `pawn`,
    position: [2, 7],
    player: `white`,
    history: [[2, 7]],
  },
  {
    id: `white-pawn-3`,
    name: `pawn`,
    position: [3, 7],
    player: `white`,
    history: [[3, 7]],
  },
  {
    id: `white-pawn-4`,
    name: `pawn`,
    position: [4, 7],
    player: `white`,
    history: [[4, 7]],
  },
  {
    id: `white-pawn-5`,
    name: `pawn`,
    position: [5, 7],
    player: `white`,
    history: [[5, 7]],
  },
  {
    id: `white-pawn-6`,
    name: `pawn`,
    position: [6, 7],
    player: `white`,
    history: [[6, 7]],
  },
  {
    id: `white-pawn-7`,
    name: `pawn`,
    position: [7, 7],
    player: `white`,
    history: [[7, 7]],
  },
  {
    id: `white-pawn-8`,
    name: `pawn`,
    position: [8, 7],
    player: `white`,
    history: [[8, 7]],
  },
  {
    id: `black-pawn-1`,
    name: `pawn`,
    position: [1, 2],
    player: `black`,
    history: [[1, 2]],
  },
  {
    id: `black-pawn-2`,
    name: `pawn`,
    position: [2, 2],
    player: `black`,
    history: [[2, 2]],
  },
  {
    id: `black-pawn-3`,
    name: `pawn`,
    position: [3, 2],
    player: `black`,
    history: [[3, 2]],
  },
  {
    id: `black-pawn-4`,
    name: `pawn`,
    position: [4, 2],
    player: `black`,
    history: [[4, 2]],
  },
  {
    id: `black-pawn-5`,
    name: `pawn`,
    position: [5, 2],
    player: `black`,
    history: [[5, 2]],
  },
  {
    id: `black-pawn-6`,
    name: `pawn`,
    position: [6, 2],
    player: `black`,
    history: [[6, 2]],
  },
  {
    id: `black-pawn-7`,
    name: `pawn`,
    position: [7, 2],
    player: `black`,
    history: [[7, 2]],
  },
  {
    id: `black-pawn-8`,
    name: `pawn`,
    position: [8, 2],
    player: `black`,
    history: [[8, 2]],
  },
  {
    id: `black-rook-1`,
    name: `rook`,
    position: [1, 1],
    player: `black`,
    history: [[1, 1]],
  },
  {
    id: `black-knight-1`,
    name: `knight`,
    position: [2, 1],
    player: `black`,
    history: [[2, 1]],
  },
  {
    id: `black-bishop-1`,
    name: `bishop`,
    position: [3, 1],
    player: `black`,
    history: [[3, 1]],
  },
  {
    id: `black-king-1`,
    name: `king`,
    position: [4, 1],
    player: `black`,
    history: [[4, 1]],
  },
  {
    id: `black-queen-1`,
    name: `queen`,
    position: [5, 1],
    player: `black`,
    history: [[5, 1]],
  },
  {
    id: `black-bishop-2`,
    name: `bishop`,
    position: [6, 1],
    player: `black`,
    history: [[6, 1]],
  },
  {
    id: `black-knight-2`,
    name: `knight`,
    position: [7, 1],
    player: `black`,
    history: [[7, 1]],
  },
  {
    id: `black-rook-2`,
    name: `rook`,
    position: [8, 1],
    player: `black`,
    history: [[8, 1]],
  },
] as Piece[]
